Dockerfile, env.example, src/common/database.py, src/plugins/chat/bot_config_toml, src/plugins/chat/config.py, src/plugins/chat/image_utils.py, src/plugins/schedule/schedule_generator.py
顺便修了部分场景环境变量没加载，现在两个地方做了相同的配置，后续修复
=> mongodb支持配置用户和密码，docker镜像使用仓库本地代码

.github/workflows/docker-image.yml, src/plugins/chat/bot_config_toml
工作流编译docker镜像时添加arm64支持，在bot_config_toml中添加更多注释
=> 添加docker镜像arm64支持

src/plugins/chat/cq_code.py
ref https://github.com/psf/requests/issues/6616
解决方案 https://quentin.pradet.me/blog/fixing-sslv3_alert_handshake_failure-with-urllib3-20.html
fix https://github.com/SengokuCola/MaiMBot/issues/11
泪目
=> 修复高版本环境TLS1.3报错

docker-compose.yml
=>  docker下麦麦的图片路径要给napcat不然发送图片会有问题

bot.py, config/bot_config_toml, src/gui/reasoning_gui.py, src/plugins/chat/__init__.py, src/plugins/chat/config.py, src/plugins/chat/llm_generator.py, src/plugins/chat/prompt_builder.py, src/plugins/chat/utils_image.py, src/plugins/knowledege/knowledge_library.py, src/plugins/memory_system/draw_memory.py, src/plugins/memory_system/llm_module.py, src/plugins/memory_system/llm_module_memory_make.py, src/plugins/memory_system/memory.py, src/plugins/memory_system/memory_make.py, src/plugins/schedule/schedule_generator.py, src/plugins/schedule/schedule_llm_module.py
=> 统一database config,修复.env未被读取问题

bot.py
=> env.prod无法加载

config/bot_config_template.toml, docs/installation.md, template.env
Reverts SengokuCola/MaiMBot#87
请修改debug分支
帮助文档在debug分支有较大改动
=> Revert "部分文本描述更改"

src/gui/reasoning_gui.py
2. - [x] 本次更新 **包含破坏性变更**（如数据库结构变更、配置文件修改等）
4. 请填写破坏性更新的具体内容（如有）:
5. 请简要说明本次更新的内容和目的：
修复推理gui报ImportError: attempted relative import with no known parent package的问题
- **截图/GIF**：
- **附加信息**:
=> Fix:推理gui报ImportError

src/plugins/chat/cq_code.py
4. 请填写破坏性更新的具体内容（如有）:
5. 请简要说明本次更新的内容和目的：
- **关联 Issue**：Close #80 
- **截图/GIF**：
- **附加信息**:
多加一处判断@全体成员的QQ字段为all
=> fix:修复无法接收At全体消息问题

docs/synology_deploy.md
增加HOST的设置教程。若不设置为0.0.0.0，可能导致napcat无法连接maimbot的WebSocket
=> docs(NAS部署指南): 增加HOST的设置，确保maimbot能被napcat访问

src/plugins/models/utils_model.py
=> fix: 优化发送错误时图片大喷射

src/plugins/schedule/schedule_generator.py
=> fix; 防止解析日程时遇到多余的内容影响解析（比如markdown代码块标记）

src/plugins/chat/__init__.py, src/plugins/chat/bot.py, src/plugins/chat/message_sender.py, src/plugins/chat/storage.py
2. - [x] 本次更新 **包含破坏性变更**（如数据库结构变更、配置文件修改等）
- **截图/GIF**：
- **附加信息**:数据库中能看见新增的条目，但是貌似模仿打断过长思考的方式不起作用
=> feat:尝试增加不回答已撤回消息的功能，并每小时删除一次存留超过1小时的撤回消息

bot.py, src/plugins/chat/bot.py, src/plugins/chat/emoji_manager.py, src/plugins/memory_system/memory.py, src/plugins/utils/logger_config.py
- ✅ 接受：部分与重构分支refractor直接相关的Bug修复：提交到refractor分支
2. - [x] 本次更新 **包含破坏性变更**（如数据库结构变更、配置文件修改等）
6. 请简要说明本次更新的内容和目的：新的logger系统
鉴于不知道是什么的问题，直接利用`logger_config.py`中的方法无法实现`logger`的格式设置声明，因此本次更新修改如下：
```python
class LogClassification(Enum): # 把原来的名称修改为LogClassification
BASE = "base"
MEMORY = "memory"
EMOJI = "emoji"
CHAT = "chat"
class LogModule:               # 此处新构建一个LogModule Class类
logger = loguru.logger.opt()
def __init__(self):
pass
...
```
注释掉原来的
```python
from loguru import logger
```
并在文件开始执行如下构造
```python
from 某处 import …
```
=> 优雅的新logger

src/plugins/chat/bot.py, src/plugins/chat/cq_code.py, src/plugins/chat/emoji_manager.py, src/plugins/chat/llm_generator.py, src/plugins/chat/message.py, src/plugins/chat/message_cq.py, src/plugins/chat/prompt_builder.py, src/plugins/chat/utils_image.py
- ✅ 接受：部分与重构分支refractor直接相关的Bug修复：提交到refractor分支
重新修复了reply消息无法发送的问题
- **截图/GIF**：
- **附加信息**:
=> fix: 修复回复，重构messageCQ中的构造为异步，增大了部分默认的max-tokens

src/plugins/models/utils_model.py
- ✅ 接受：部分与重构分支refractor直接相关的Bug修复：提交到refractor分支
当bot要处理一个空格消息，获取embedding向量会发生报错
- **截图/GIF**：
- **附加信息**:
=> Fix:当bot要处理一个空格消息，获取embedding向量会发生报错

src/plugins/chat/message.py
修复_generate_detailed_text函数中的错误判断，修复当群昵称不存在时，bot将群昵称视为”None“的问题。
- **截图/GIF**：
- **附加信息**:
=> Fix:修复当群昵称不存在时，bot将群昵称视为”None“

.gitignore, src/plugins/remote/__init__.py, src/plugins/remote/remote.py
6. 请简要说明本次更新的内容和目的：新增插件remote，用于客户端在线数量统计（目前处于测试阶段）
- **截图/GIF**：
- **附加信息**:
=> feat: 客户端在线统计

src/plugins/remote/__init__.py, src/plugins/remote/remote.py
6. 请简要说明本次更新的内容和目的：单独创建心跳线程防止阻塞主线程
- **截图/GIF**：
- **附加信息**:
=> fix: 单独创建心跳线程防止阻塞主线程

run.sh
适配最新的分支结构
- **截图/GIF**：
- **附加信息**:
=> fix: Linux一键安装脚本适配新的分支结构

webui.py
=> fix: 修复了重复保存可能会清空list内容的bug,优化了界面布局(我TM修修修修修)

src/gui/logger_gui.py
添加了一个方便查看日志的GUI（用的是项目本身的依赖customtkinter）
- 可以实时筛选日志等级、模块名对应的行
- 可以隐藏时间、日志等级、模块对应的列
- 单个新文件更新，不涉及麦麦本身代码，不会影响目前进行的重构
- **截图/GIF**：
- **附加信息**:
=> 新增GUI：日志查看器（不影响任何现有功能）

docs/fast_q_a.md
6. 请简要说明本次更新的内容和目的：qa markdown格式修正
- **截图/GIF**：
- **附加信息**:
=> 修改qa格式，简直灾难

src/plugins/memory_system/memory_manual_build.py, src/plugins/personality/can_i_recog_u.py, src/plugins/personality/renqingziji_with_mymy.py, src/plugins/personality/who_r_u.py, src/plugins/willing/mode_classical.py
3. - [ ] 本次更新是否经过测试
- **截图/GIF**：
- **附加信息**:
=> secret 神秘小测验加强版

src/plugins/chat/relationship_manager.py
- **关联 Issue**：Close #564 
- **截图/GIF**：
- **附加信息**:
=> fix: minor fix for 564

src/think_flow_demo/current_mind.py, src/think_flow_demo/heartflow.py, template/bot_config_template.toml
3. - [ ] 本次更新是否经过测试
- **截图/GIF**：
- **附加信息**:
=> fix 思维流不会自动停止消耗token

src/think_flow_demo/heartflow.py
3. - [ ] 本次更新是否经过测试
- **截图/GIF**：
- **附加信息**:
=> fix: 同步心流与本体使用的prompt，保持人设一致（刚刚少改了个文件）

src/plugins/config/config.py
3. - [ ] 本次更新是否经过测试
- **截图/GIF**：
- **附加信息**:
=> version update

src/common/database/database.py, src/common/database/database_model.py, src/config/config.py, src/config/official_configs.py, template/bot_config_template.toml
- ✅ 接受：与main直接相关的Bug修复：提交到dev分支
- 新增功能类pr需要经过issue提前讨论，否则不会被合并
2. - [ ] 我确认我阅读了贡献指南
3. - [ ] 本次更新类型为：BUG修复
4. - [ ] 本次更新是否经过测试
- **截图/GIF**：
- **附加信息**:
=> Revert "feat(database): 添加MySQL支持并重构数据库配置"
